name: "Scrape"

on:  
  # workflow_dispatch:
  schedule:
  - cron: "0 4 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute the scraper
      run: python scrape.py

    - name: Commit changes
      run: |
        git config --global user.email "dev@asjordi.dev"
        git config --global user.name "Jordi Ayala"
        git add data/
        git diff --staged --quiet || git commit -m 'chore: :card_file_box: Update dataset'
        git push